---
- name: Set MariaDB socket
  set_fact:
    mariadb_socket: '/var/lib/mysql/mysql.sock'

- name: Insert Venom local vars
  template:
    src: 'templates/local.yml.j2'
    dest: '{{ venom_dir }}/vars/local.yml'
    mode: '0644'
    owner: 'root'
    group: 'root'
