name: Signe debian package
on:
  workflow_call:
    inputs:
      _VOLUME_MOUNT:
        required: True
        type: string
      _IMAGE_TYPE:
        required: True
        type: string
      _BRANCH_NAME:
        required: True
        type: string
      _PACKAGE_NAME:
        required: True
        type: string


jobs:
  sign_package_deb:
    if: inputs._IMAGE_TYPE == 'debian'
    runs-on: packetfence-perl-package-build 
    container:
      image: debian:11.0
      volumes:
        - ${{ inputs._VOLUME_MOUNT }}/debian/packages/:/mnt
    steps:
      - name: Download artifactory ${{ inputs._IMAGE_TYPE }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACTORY_NAME }}
          path:  /mnt
        env:
          ARTIFACTORY_NAME: ${{ inputs._IMAGE_TYPE == 'rhel8' && 'package-rpm' || 'package-deb' }}

      - name: Install debian dependenecies ${{ inputs._IMAGE_TYPE }}
        run:  apt update && apt install gpg dpkg-sig -y

      - name: import private key ${{ inputs._IMAGE_TYPE }}
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --pinentry-mode loopback --import

      - name: Sign the package ${{ inputs._IMAGE_TYPE }}
        run: dpkg-sig -k  B022C48D3D6373D7FC256A8CCB2D3A2AA0030E2C  --sign builder /mnt/${{ inputs._PACKAGE_NAME }}*.deb

      - name: Verifiy the signarure of package ${{ inputs._IMAGE_TYPE }}
        run: gpg --verify  /mnt/${{ inputs._PACKAGE_NAME }}*.deb

  upload_packages:
    uses:  ./.github/workflows/reusable_upload_packages.yml
    needs: sign_package_deb
    with:
      _IMAGE_TYPE: ${{ inputs._IMAGE_TYPE }}
      _VOLUME_MOUNT: ${{ inputs._VOLUME_MOUNT }}
      _BRANCH_NAME: ${{ inputs._BRANCH_NAME }}
      _PACKAGE_NAME: ${{ inputs._PACKAGE_NAME }}
    secrets: inherit