name: Reusable unit test
on:
  workflow_call:
    inputs:
      _IMAGE_TYPE:
        required: True
        type: string
      _PACKAGE_NAME:
        required: True
        type: string

jobs:
  unit-test:
    runs-on: packetfence-perl-package-build 
    container:
      image:  ${{ inputs._IMAGE_TYPE == 'rhel8' && 'redhat/ubi8' || 'debian:11.0'}}
    steps:     
      - name: download artifactory ${{ inputs._IMAGE_TYPE }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACTORY_NAME }}
          path:  /mnt
        env:
          ARTIFACTORY_NAME: ${{ inputs._IMAGE_TYPE == 'rhel8' && 'package-rpm' || 'package-deb' }}

      - name: Install the package packetfence-perl ${{ inputs._IMAGE_TYPE }}
        run: |
          ls -la /mnt
          ${{ inputs._IMAGE_TYPE == 'rhel8' && env.INSATALL_RPM_PACKAGE  || env.INSALL_DEB_PACKAGE }}
        env:
          INSATALL_RPM_PACKAGE: "set -x && yum -y install findutils && find /mnt -name ${{ inputs._PACKAGE_NAME }}*.rpm -exec rpm -ivh {} \\;"
          INSALL_DEB_PACKAGE: "set -x && find /mnt -name ${{ inputs._PACKAGE_NAME }}*.deb -exec dpkg -i {} \\;"
          

