name: Signe debian package
on:
  workflow_call:
    inputs:
      _VOLUME_MOUNT:
        required: True
        type: string
      _IMAGE_TYPE:
        required: True
        type: string


jobs:
  sign_package_deb:
    if: inputs._IMAGE_TYPE == 'debian'
    runs-on: packetfence-perl-deb-package-build
    container:
      image: debian:11.0
      volumes:
        - ${{ inputs._VOLUME_MOUNT }}/debian/packages/:/mnt
    steps:
      - name: Install debian dependenecies
        run:  apt update && apt install gpg dpkg-sig -y

      - name: import private key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --pinentry-mode loopback --import

      - name: Sign the package
        run: dpkg-sig -k  B022C48D3D6373D7FC256A8CCB2D3A2AA0030E2C  --sign builder /mnt/*.deb

      - name: Verifiy the signarure of package
        run: gpg --verify  /mnt/*.deb