name: Sign rpm package 
on:
  workflow_call:
    inputs:
      _IMAGE_TYPE:
        required: True
        type: string
      _VOLUME_MOUNT:
        required: True
        type: string
      


jobs:
  sign_package_rpm:
    runs-on: packetfence-perl-rpm-package-build
    if: inputs._IMAGE_TYPE == 'rhel8'
    container:
      image: rockylinux:8.8
      volumes:
        - ${{ inputs._VOLUME_MOUNT }}/rhel8/packages/:/mnt
    steps:
      - name: Install dependenecies
        run: yum install -y rpm-sign

      - name: import private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --pinentry-mode loopback --import

      - name: Check if the key was imported
        run: |
          rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
          gpg --list-keys

      - name: Sign the package
        run: rpm --define "_gpg_name support@inverse.ca" --define '_signature gpg' --addsign  /mnt/packetfence-perl*.rpm

      - name: Verifiy the signarure of package
        run: |
          gpg  --batch --yes   --output /tmp/pubkey.pub --armor --export  support@inverse.ca && rpm --import /tmp/pubkey.pub
          rpm -qpi /mnt/packetfence-perl*.rpm
          rpm --checksig /mnt/packetfence-perl*.rpm