name: Reusable workflow
on:
  workflow_call:
    inputs:
      _IMAGE_TYPE:
        required: True
        type: string
      _VOLUME_MOUNT:
        required: True
        type: string
      

jobs:
  unit-test:
    runs-on: packetfence-perl-rpm-package-build
    container:
      image:  ${{ inputs._IMAGE_TYPE == 'rhel8' && 'redhat/ubi8' || 'debian:11.0'}}
      volumes:
        - ${{ inputs._VOLUME_MOUNT }}/${{inputs._IMAGE_TYPE}}/packages/:/mnt
    steps:     
      - name: Install the package packetfence-perl
        run: |
          ls -la /mnt
          ${{ env.COMMAND_INSTALL }}
        env:
          COMMAND_INSTALL: ${{ inputs._IMAGE_TYPE == 'rhel8' &&  'yum -y install findutils && find /mnt -name "packetfence-perl-*.rpm" -exec rpm -ivh {} \;' || 'find /mnt -name "packetfence-perl*.deb" -exec dpkg -i {} \;' }}
